version: 2.1
orbs:
  cypress: cypress-io/cypress@1.20.0
  aws-s3: circleci/aws-s3@1.0.11
jobs: 
  build:
    docker:
    - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  regression_test:
    docker:
    - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: yarn install
      - run: sed -i '/process.env.CI/,+7 d' node_modules/react-scripts/scripts/start.js
      - run: yarn ci:cypress-regression
  smoke_test:
    docker:
    - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: yarn install
      - run: sed -i '/process.env.CI/,+7 d' node_modules/react-scripts/scripts/start.js
      - run: yarn ci:cypress-smoke
  deploy:
    docker:
    - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - aws-s3/sync:
          from: build
          to: 's3://maxharding4.com/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=43200"
          overwrite: true
      - run: aws cloudfront create-invalidation --distribution-id=E18D7W5LICE64E --paths /index.html
      - run: aws cloudfront create-invalidation --distribution-id=E18D7W5LICE64E --paths /service-worker.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - cypress/run:
          requires:
            - build
          command: yarn ci:cypress-regression
          store_artifacts: true
          post-steps:
            - store_test_results:
                path: cypress/results
      - deploy:
          requires:
            - regression_test
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - smoke_test:
          requires:
            - build