version: 2.1
orbs:
  cypress: cypress-io/cypress@1.19.1
  aws-s3: circleci/aws-s3@1.0.11
jobs: 
  build:
    docker:
    - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
    - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: yarn ci:cypress-run
  deploy:
    docker:
    - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - aws-s3/sync:
          from: build
          to: 's3://maxharding4/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=43200"
          overwrite: true
      - run: aws cloudfront create-invalidation --distribution-id=EOA1ZN68DNT68 --paths /index.html
      - run: aws cloudfront create-invalidation --distribution-id=EOA1ZN68DNT68 --paths /service-worker.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - test:
          requires:
            - build