version: 2.1
orbs:
  cypress: cypress-io/cypress@1.20.0
  aws-s3: circleci/aws-s3@1.0.11
defaults: &defaults
  docker:
    - image: circleci/node:12.9.1-browsers
  working_directory: ~/repo

commands:
  cypress_install:
    steps:
      restore_cache:
        key: cypress-binary-{{ checksum "yarn.lock" }}
      restore_cache:
        key: node-modules-{{ checksum "yarn.lock" }}
    - run:
          name: Install dependencies
          command: yarn install
    - run:
          name: Ensure cypress binary is installed
          command: ./node_modules/cypress/bin/cypress install

  cypress_cleanup:
    steps:
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - save_cache:
          key: cypress-binary-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/Cypress
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  apply_hack:
    steps:
      - run:
          command: sed -i '/process.env.CI/,+7 d' node_modules/react-scripts/scripts/start.js

  smoke_tests:
    steps:
      - run:
          command: yarn ci:cypress-smoke

  regression_tests:
    steps:
      - run:
          command: yarn ci:cypress-regression

jobs: 
  build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  regression_test:
    <<: *defaults
    steps:
      - cypress install
      - apply_hack
      - regression_tests
      - cypress_cleanup

  smoke_test:
    <<: *defaults
    steps:
      - cypress install
      - apply_hack
      - smoke_tests
      - cypress_cleanup

  deploy:
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - aws-s3/sync:
          from: build
          to: 's3://maxharding4.com/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=43200"
          overwrite: true
      - run: aws cloudfront create-invalidation --distribution-id=E18D7W5LICE64E --paths /index.html
      - run: aws cloudfront create-invalidation --distribution-id=E18D7W5LICE64E --paths /service-worker.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - regression_test:
          requires:
            - build
      - deploy:
          requires:
            - regression_test
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - smoke_test:
          requires:
            - build