version: 2.1
orbs:
  cypress: cypress-io/cypress@1.19.1
  aws-s3: circleci/aws-s3@1.0.11
jobs: 
  build:
    docker:
    - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
    - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: yarn ci:cypress-run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master